pulp/pulp_docker

- AUTHORS
- common/pulp_docker/common/error_codes.py
- plugins/pulp_docker/plugins/distributors/configuration.py
- plugins/pulp_docker/plugins/distributors/distributor_export.py
- plugins/pulp_docker/plugins/distributors/distributor_web.py
- plugins/test/unit/plugins/distributors/test_configuration.py
- plugins/test/unit/plugins/distributors/test_distributor_export.py
- plugins/test/unit/plugins/distributors/test_distributor_web.py
[BZ -1148556](https://bugzilla.redhat.com/show_bug.cgi?id=1148556)
Docker registry id's cannot contain uppercase letters, so they should be validated. If the repo-registry-id is not specified, it defaults to repo id, so in that case, the repo-id needs to be validated differently.
This PR gives a less than ideal error back to the user. This problem is fixed in https://github.com/pulp/pulp/pull/1487
> 1148556 - Validate repo-registry-id to ensure compatibility with Docker

- common/pulp_docker/common/error_codes.py
- plugins/pulp_docker/plugins/distributors/configuration.py
- plugins/test/unit/plugins/distributors/test_configuration.py
Docker repository names may only contain letters numbers, hyphens, underscores, and periods; however, the `repo_registry_id` field in pulp can also contain a namespace, ex `namespace/repo_name`, so the validation should allow a single slash.
> 1148556 - part2 - repo registry ids may contain slashes

- plugins/pulp_docker/plugins/importers/importer.py
Platform had some silly imports in pulp.plugins that were only there so
that plugins don't import pulp.server. These imports were angering
flake8 (for good reason). This commit fixes the imports so
they import from the real place that the code lived.
> Respond to PEP-8 changes in platform.

- common/pulp_docker/common/error_codes.py
- plugins/pulp_docker/plugins/registry.py
- plugins/test/unit/plugins/test_registry.py
- pulp-docker.spec
This depends on changes in pulp that better-handle PulpCodedException reporting.
fixes #702
refs #652
https://pulp.plan.io/issues/652
https://pulp.plan.io/issues/702
https://github.com/pulp/pulp/pull/1772
> Failure to sync no longer logs tracebacks, also reports a more helpful message

- plugins/pulp_docker/plugins/registry.py
- plugins/test/unit/plugins/test_registry.py
This uses the new API.
https://pulp.plan.io/issues/914
closes #914
> The API for fetching tags from a remote registry or index changed.

- common/pulp_docker/common/error_codes.py
Fixes the wording of an error message.
re: 291
https://pulp.plan.io/issues/291
> Correct the repo-registry-id validation error

- docs/user-guide/recipes.rst
I also changed all the docs and messages not to confuse the users. I did not touch any variables' or methods' name.
closes #966
https://pulp.plan.io/issues/966
> Fixing discrepancy "canceled" vs. "cancelled

- common/pulp_docker/common/models.py
- common/test/unit/test_models.py
- plugins/pulp_docker/plugins/importers/sync.py
- plugins/pulp_docker/plugins/importers/v1_sync.py
- plugins/test/unit/plugins/importers/test_sync.py
- plugins/test/unit/plugins/importers/test_v1_sync.py
- plugins/types/docker.json
This commit introduces a new Unit type called Blob, and converts the
Docker v2 sync code to use it instead of overloading the Image model
that is also used by v1 sync and publish. This will simplify the
concepts in Pulp and make the v2 distributor easier to write.
Conveniently, it also separates the locations of the Units on the
filesystem as well.
https://pulp.plan.io/issues/967
re #967
> Create a new Blob model.

- common/pulp_docker/common/models.py
- extensions_admin/pulp_docker/extensions/admin/manifest.py
- extensions_admin/pulp_docker/extensions/admin/pulp_cli.py
- extensions_admin/test/unit/extensions/admin/test_manifest.py
- plugins/pulp_docker/plugins/importers/importer.py
- plugins/test/unit/plugins/importers/test_importer.py
https://pulp.plan.io/issues/1203
The PR consolidates:
- https://pulp.plan.io/issues/1175
- https://pulp.plan.io/issues/1176
Add support for manifest list (search), copy and remove.  This includes changes to the importer and adds manifest commands.  If we decided to release this as docker 2.0, we should refactor the commands to match what the rpm commands do.  That is, make *search*, *copy* and *remove* sections and add type specified commands to those sections like:
```
pulp-admin docker repo search manifest --repo-id=elvis
pulp-admin docker repo copy manifest --repo-id=elvis
pulp-admin docker repo remove manifest --repo-id=elvis
```
instead of:
```
pulp-admin docker repo manifest search --repo-id=elvis
pulp-admin docker repo manifest copy --repo-id=elvis
pulp-admin docker repo manifest …
```
> Add support for manifest search, copy and remove.

- extensions_admin/pulp_docker/extensions/admin/images.py
- extensions_admin/pulp_docker/extensions/admin/manifest.py
- extensions_admin/pulp_docker/extensions/admin/pulp_cli.py
- extensions_admin/test/unit/extensions/admin/test_manifest.py
- extensions_admin/test/unit/extensions/admin/test_pulp_cli.py
https://pulp.plan.io/issues/1219
Now that docker 2.0 repositories contain multiple content types (images, manifests), the repo sections and commands needed to be rearranged as:
```
pulp-admin docker repo search (image|manifest)
pulp-admin docker repo copy (image|manifest)
pulp-admin docker repo remove (image|manifest)
```
Instead of:
```
pulp-admin docker repo images
pulp-admin docker repo copy
pulp-admin docker repo remove
pulp-admin docker repo manifest search
pulp-admin docker repo manifest copy
pulp-admin docker repo manifest remove
```
> Command and section layout consistent with other plugins.

- plugins/etc/httpd/conf.d/pulp_docker.conf
This commit adjusts our Docker v2 endpoint to be served at
/pulp/docker/v2 instead of just /v2. It was necessary to also adjust the
Docker v1 endpoint to be /pulp/docker/v1 instead of just /pulp/docker.
This is a backwards-incompatible change.
The Docker v1 endpoint was configured to require SSL. The v2 endpoint is currently configured to allow plaintext and SSL. Should we configure v2 to similarly require SSL?
> Serve Docker v2 at /pulp/docker/v2 instead of /v2.

- common/pulp_docker/common/models.py
- common/test/unit/test_models.py
- plugins/pulp_docker/plugins/migrations/0001_v2_support.py
- plugins/setup.py
- plugins/test/unit/plugins/importers/test_v1_sync.py
This commit includes a migration that allows users to migrate from
pulp-docker-1.x to pulp-docker-2.0.0.
https://pulp.plan.io/issues/1217
re #1217
> Add a migration for users to move to pulp-docker-2

- plugins/pulp_docker/plugins/distributors/configuration.py
- plugins/pulp_docker/plugins/distributors/metadata.py
- plugins/pulp_docker/plugins/distributors/publish_steps.py
- plugins/test/unit/plugins/distributors/test_configuration.py
The redirect URLs generated by the distributor did not include the Docker API version, which would lead to 404s. This
commit adds the Docker API version to the URLs.
https://pulp.plan.io/issues/1265
fixes #1265
> Form the redirect URL using the Docker API version.

- plugins/pulp_docker/plugins/distributors/publish_steps.py
- plugins/pulp_docker/plugins/distributors/v1_publish_steps.py
- plugins/test/unit/plugins/distributors/test_v1_publish_steps.py
This commit makes each of the top level (v1 and v2) steps have their own separate working space, so that they do not
share files during the atomic publish.
https://pulp.plan.io/issues/1241
fixes #1241
> Have each step use its own space inside the working_dir.

- plugins/etc/httpd/conf.d/pulp_docker.conf
This commit fixes a few issues with the httpd configuration for Docker v2:
* Docker is written in Go and thus it suffers from this bug:
https://github.com/golang/go/issues/5742
This commit removes most SSL directives from the httpd configuration because they were causing httpd to want to
renegotiate with the client (causing the issue), and they were unnecessary to begin with. The SSL options in the
config did not make much sense. They did things like exporting the client certificate into the environment, when
this config only serves flat files. It also had strange client certificate settings when client certificates are
not required for these views.
* The default httpd configuration in Fedora uses mod_mime_magic, which adds content-type and content-encoding
headers to the responses. These …
> Reconfigure the httpd vhost to better suit the Docker client.

- plugins/pulp_docker/plugins/distributors/distributor_export.py
- plugins/pulp_docker/plugins/distributors/distributor_web.py
This commit fixes an issue where users were unable to delete docker repositories.
Thanks to Jindrich Luza for the report and for the fix!
https://pulp.plan.io/issues/1331
fixes #1331
> Fix repo deletion.

- plugins/pulp_docker/plugins/importers/importer.py
- plugins/pulp_docker/plugins/importers/sync.py
- plugins/pulp_docker/plugins/importers/v1_sync.py
- plugins/test/unit/plugins/importers/test_importer.py
- plugins/test/unit/plugins/importers/test_sync.py
https://pulp.plan.io/issues/1453
I tested sync and publish with v1 and v2 registries.
Should be merged after:
https://github.com/pulp/pulp/pull/2291
https://github.com/pulp/pulp/pull/2289
> passing new-style Repo object to controllers & saving before import_content

- common/pulp_docker/common/constants.py
- common/pulp_docker/common/error_codes.py
- docs/tech-reference/importer.rst
- extensions_admin/pulp_docker/extensions/admin/cudl.py
- extensions_admin/test/unit/extensions/admin/test_cudl.py
- plugins/pulp_docker/plugins/importers/importer.py
- plugins/pulp_docker/plugins/importers/sync.py
- plugins/pulp_docker/plugins/importers/v1_sync.py
- plugins/pulp_docker/plugins/registry.py
- plugins/test/unit/plugins/importers/test_importer.py
- plugins/test/unit/plugins/importers/test_sync.py
- plugins/test/unit/plugins/importers/test_v1_sync.py
- plugins/test/unit/plugins/test_registry.py
fixes #1449
https://pulp.plan.io/issues/1449
I combined the root v1 and v2 sync steps into one. The step system requires a
single root step, and only one layer of children can report status and
progress. This required the refactor, combining each collection of steps onto
one parent.
> Can sync v1 and v2 APIs together, and optionally disable v1 sync

- plugins/pulp_docker/plugins/importers/sync.py
- plugins/pulp_docker/plugins/importers/v1_sync.py
- plugins/test/unit/plugins/importers/test_sync.py
Call save_and_import_content().
Utilize cleanup pattern instead where usage doesn't
fit.
re #[1457](https://pulp.plan.io/issues/1457)
https://pulp.plan.io/issues/1457
> Ensure file objects are cleaned up on error

- plugins/pulp_docker/plugins/importers/importer.py
- plugins/pulp_docker/plugins/importers/sync.py
- plugins/pulp_docker/plugins/registry.py
- plugins/test/unit/plugins/importers/test_importer.py
- plugins/test/unit/plugins/importers/test_sync.py
- plugins/test/unit/plugins/test_registry.py
pulp-docker used to try v2 and fall back to v1 if v2 was not
supported. This commit causes pulp-docker to sync both for
registries that support them.
https://pulp.plan.io/issues/1449
re #1449
> Sync v1 and v2 content when the registry support it.

- plugins/pulp_docker/plugins/migrations/0001_v2_support.py
closes #1492
https://pulp.plan.io/issues/1492
> 1492 - migration fails when /v1 directory already exists

- docs/user-guide/recipes.rst
closes #1598
https://pulp.plan.io/issues/1598
> 1598 - Clarify in docs that index.docker.io only supported for v1

- plugins/pulp_docker/plugins/importers/sync.py
- plugins/pulp_docker/plugins/registry.py
- plugins/pulp_docker/plugins/token_util.py
- plugins/test/unit/plugins/importers/test_sync.py
- plugins/test/unit/plugins/test_token_util.py
closes: #1144
https://pulp.plan.io/issues/1596
https://pulp.plan.io/issues/1144
Note: This will hang indefinitely due to https://pulp.plan.io/issues/1567, so Nectar will need to be rebuilt for this to function correctly. @ipanova
> Make requests to docker registry with bearer tokens

- plugins/pulp_docker/plugins/registry.py
- plugins/test/unit/plugins/test_registry.py
Add library namespace to docker hub registry images that do not
have one.
closes #1404
https://pulp.plan.io/issues/1404
> Add library namespace to docker hub images

- plugins/pulp_docker/plugins/models.py
This uniqueness contstraint is now enforced by the platform for all content units.
https://pulp.plan.io/issues/1477
re: 1477
> Removes uniqueness constraint on unit key

- plugins/pulp_docker/plugins/importers/importer.py
- plugins/test/unit/plugins/importers/test_importer.py
https://pulp.plan.io/issues/1648
fixes #1648
> Pass the old-style repo object to the UploadStep.

- plugins/pulp_docker/plugins/registry.py
Static method Manifest.digest was renamed to Manfiest.calculate_digest 
in the mongoengine conversion
closes #1672
https://pulp.plan.io/issues/1672
> Manifest.digest static method was renamed

- common/pulp_docker/common/error_codes.py
- docs/user-guide/release-notes/2.0.x.rst
- plugins/pulp_docker/plugins/importers/sync.py
- plugins/pulp_docker/plugins/registry.py
- plugins/test/unit/plugins/importers/test_sync.py
- plugins/test/unit/plugins/test_registry.py
https://pulp.plan.io/issues/1831
fixes #1831
> When a sync cannot get tags from a v2 API, it will fail with a reasonable message.

- plugins/pulp_docker/plugins/importers/sync.py
- plugins/pulp_docker/plugins/registry.py
- plugins/pulp_docker/plugins/token_util.py
- plugins/test/unit/plugins/test_token_util.py
closes #1644 https://pulp.plan.io/issues/1644
closes #1646 https://pulp.plan.io/issues/1646
Allow Nectar to download with multiple threads at the same time, and
allow each thread to have and reuse its own bearer token. Also
addresses the possibility of infinite recursion if a download remains
unauthorized after retrieving a new token.
> Download docker blobs in parallel

- plugins/pulp_docker/plugins/migrations/0002_standard_storage_path.py
- plugins/test/unit/plugins/migrations/test_0002_standard_storage_path.py
https://pulp.plan.io/issues/1647
See publisher here: https://github.com/pulp/pulp_docker/blob/2.0-dev/plugins/pulp_docker/plugins/distributors/v1_publish_steps.py#L107
> Migrate docker v1 image published links.

- docs/Makefile
- docs/conf.py
- docs/user-guide/configuration.rst
- docs/user-guide/installation.rst
Intersphinx was preventing the strict mode from being enabled
due to docs being built in a network isolated mock environment.
Intersphinx was also going to break because it is tied
to URLs from ReadTheDocs. Now intersphinx is removed.
Strict Sphinx mode is now enabled.
Links are also updated to point to docs.pulpproject.org
https://pulp.plan.io/issues/2034
re #2034
> Remove intersphinx and enable Strict mode

- plugins/pulp_docker/plugins/importers/v1_sync.py
- plugins/test/unit/plugins/importers/test_v1_sync.py
- plugins/test/unit/plugins/migrations/test_0002_standard_storage_path.py
closes #1925
https://pulp.plan.io/issues/1925
> Add check for duplicate unit key during v1 sync.

- plugins/pulp_docker/plugins/migrations/0002_standard_storage_path.py
Migration 2 can take a long time. This outputs a banner to
the logs and the foreground of pulp-manage-db warning the user
that it could take a long time.
https://pulp.plan.io/issues/2060
re #2060
> Adds banner warning about migration runtime

- docs/user-guide/release-notes/2.1.x.rst
- extensions_admin/pulp_docker/extensions/admin/cudl.py
- plugins/pulp_docker/plugins/importers/sync.py
- plugins/pulp_docker/plugins/registry.py
Allow users to include basic auth credentials in the importer config
which are used to sync private repositories.
> Add basic auth to docker token request

- common/pulp_docker/common/error_codes.py
- docs/tech-reference/distributor.rst
- plugins/pulp_docker/plugins/distributors/configuration.py
- plugins/pulp_docker/plugins/distributors/publish_steps.py
- plugins/pulp_docker/plugins/distributors/rsync_distributor.py
- plugins/pulp_docker/plugins/distributors/v1_publish_steps.py
- plugins/pulp_docker/plugins/models.py
- plugins/setup.py
- pulp-docker.spec
This commit adds the docker rsync distributor. However, publishing with the docker rsync distributor does not affect the publish with the web distributor. Separate commit will bring in that functionality.
re #1887
https://pulp.plan.io/issues/1887
> Adds rsync distributor

- docs/tech-reference/distributor.rst
- plugins/pulp_docker/plugins/distributors/configuration.py
- plugins/pulp_docker/plugins/distributors/publish_steps.py
re #1887
https://pulp.plan.io/issues/1887
> Adds support for relative_repo_path for the docker rsync distributor

- docs/tech-reference/distributor.rst
re #1887
https://pulp.plan.io/issues/1887
> Removes docs referencing use of password authentication for rsync

- docs/tech-reference/distributor.rst
- docs/tech-reference/tags.rst
- docs/user-guide/recipes.rst
- docs/user-guide/release-notes/2.4.x.rst
- docs/user-guide/release-notes/index.rst
- extensions_admin/pulp_docker/extensions/admin/upload.py
- plugins/etc/httpd/conf.d/pulp_docker.conf
- plugins/pulp_docker/plugins/distributors/publish_steps.py
- plugins/pulp_docker/plugins/importers/importer.py
- plugins/pulp_docker/plugins/importers/sync.py
- plugins/pulp_docker/plugins/importers/upload.py
- plugins/pulp_docker/plugins/migrations/0003_tag_schema_change.py
- plugins/pulp_docker/plugins/models.py
- plugins/pulp_docker/plugins/registry.py
- plugins/test/data/manifest_schema2_one_layer.json
- plugins/test/unit/plugins/distributors/test_distributor_export.py
- plugins/test/unit/plugins/distributors/test_distributor_web.py
- plugins/test/unit/plugins/importers/test_sync.py
- plugins/test/unit/plugins/migrations/test_0003_tag_schema_change.py
- plugins/test/unit/plugins/test_models.py
- plugins/test/unit/plugins/test_registry.py
> As a user, I can sync manifests schema version 2. 

- pulp-docker.spec
Add provides for python2-* packages.  Fedora downstream packages are
named python2-* and provide python-*.  Upstream needs to mirror this for
dependency resolution to work properly
re #2687
> Add provides for python2-* packages

- pulp-docker.spec
The Source0 currently does not lead to the correct source file.
This updates the spec file and renames the source to what would be
the expected source name.
ref #2784
https://pulp.plan.io/issues/2784
> Update spec files Source0

- AUTHORS
- docs/tech-reference/distributor.rst
'relative_repo_path' in docs should be
'repo_relative_path'
fixes #2678
> Rectify repo relative path in docs

- extensions_admin/pulp_docker/extensions/admin/cudl.py
v1 content isn't synced by default. Hence, the
help text should state defaults to "false"
closes #2724
> `docker repo create --help` states v1 content is synced by default

- common/pulp_docker/common/constants.py
- plugins/pulp_docker/plugins/distributors/distributor_web.py
- plugins/pulp_docker/plugins/distributors/rsync_distributor.py
- plugins/test/unit/plugins/distributors/test_distributor_web.py
The types supported by docker_distributor_web include
docker_blob, docker_manifest, docker_tag
closes #3241
https://pulp.plan.io/issues/3241
> docker_distributor_web advertises supporting v2 unit types

- plugins/pulp_docker/plugins/distributors/publish_steps.py
In python, I find that passing a data structure to a function/class makes me
think the function/class has a local copy of it.
In the case of redirect_data, the parent step should "own" the data structure,
and child steps should "reach" into the parent to fetch it, instead of using
a locally stored reference. Then it's more obvious that it's a "borrowed"
data structure and its change should be visible to sibling steps.
> Do not pass a data structure to a function and mutate it.

- common/pulp_docker/common/error_codes.py
- plugins/pulp_docker/plugins/importers/upload.py
- plugins/test/unit/plugins/importers/test_upload.py
Raise a validation exception if name or manifest_digest are missing.
Added tests.
closes #3250
https://pulp.plan.io/issues/3250
> Prefer manifest_digest over digest, the actual field name on the model.

- docs/tech-reference/distributor.rst
F27+ changed the behavior of semanage to set a selinux boolean by
default, but not change its current state. Update docs to advise users
of this to avoid confusion when rsync distributors fail to run with
selinux in F27.
re #3347
https://pulp.plan.io/issues/3347
> Advise users on using setsebool to set pulp_manage_rsync selinux boolean

- AUTHORS
- plugins/pulp_docker/plugins/distributors/publish_steps.py
- plugins/test/unit/plugins/distributors/test_publish_steps.py
Previously, the last two steps of docker v2 publish were:
- Put symlink in place pointing at redirect file under master directory
- Create the redirect file
That means there's a period of time during publish where the redirect
file for the repo doesn't exist at the expected path.  If crane loads
metadata at this time, it will fail to load metadata for the repo.
This commit fixes the issue by moving the symlink rewrite to the last
step.
closes #3357
https://pulp.plan.io/issues/3357
> Fix docker v2 publish race

- plugins/pulp_docker/plugins/importers/importer.py
Each tag exists in only a single repository, so when they are removed,
they are automatically orphaned. By cleaning them up when they are
removed, we solve a problem in which orphaned tags were erroneously
published.
fixes #3462
https://pulp.plan.io/issues/3462
> Delete tags when they are unassociated from a repository

- docs/user-guide/recipes.rst
- docs/user-guide/release-notes/3.2.x.rst
- docs/user-guide/release-notes/index.rst
- plugins/pulp_docker/plugins/importers/upload.py
- plugins/test/unit/plugins/importers/test_upload.py
https://pulp.plan.io/issues/3497
Support upload of tarball with incomplete layers.
The `AddUnits.process_main()` is doing too much and needs to be refactored but outside the scope of this story.  Copied and pasted most of the added unit test as well.
> Support upload of tarball with incomplete layers.

- common/pulp_docker/common/dir_transport.py
- common/test/unit/test_dir_transport.py
- plugins/pulp_docker/plugins/importers/upload.py
- plugins/test/unit/plugins/importers/test_upload.py
https://github.com/containers/image/pull/419 removed the expectation that the file ends in .tar and skopeo followed suit. 
https://pulp.plan.io/issues/3703
Unless we need to remain compatible with older versions of skopeo, I think we are ok to make the simple change here.
> Don't expect .tar in path for Directory Transport 1.1+

- common/pulp_docker/common/dir_transport.py
- common/test/unit/test_dir_transport.py
- plugins/pulp_docker/plugins/importers/upload.py
- plugins/test/unit/plugins/importers/test_upload.py
Adds comparators for a new class Version which represents a skopeo
directory transport version. This will allow us to easily support
future changes.
https://github.com/containers/image/pull/419
fixes: #3703
> [Cherry-Pick] Read/use Directory Transport version from Skopeo

- plugins/pulp_docker/plugins/importers/upload.py
closes #3904
https://pulp.plan.io/issues/3904
I can't get crane to work, so the pulpsmash tests keep failing with
```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.121.29', port=5000): Max retries exceeded with url: /v2/d55d3ced-d1cf-4c3d-b9a7-0a2777657cbe/manifests/latest (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb79a148940>: Failed to establish a new connection: [Errno 111] Connection refused',))
```
But I did manually test this change with 
`pulp-admin docker repo uploads upload --repo-id=busybox -f manifest_list.json`
where the manifest_list.json is:
```
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
"manifests": [
{
"mediaType": …
```
> Fix upload issue with embeddedmanifests

- plugins/pulp_docker/plugins/importers/upload.py
- plugins/test/unit/plugins/importers/test_upload.py
https://pulp.plan.io/issues/3910
json.load and json.dump reorderes manifest file.
The "signatures" field is supposed to be at the end of the JSON, because docker while
stripping the signatures operates on the raw bytes of the data, without regard to JSON
structure.
> closes #3910

- pulp_docker/app/models.py
- pulp_docker/app/serializers.py
- pulp_docker/app/tasks/synchronizing.py
- pulp_docker/app/viewsets.py
https://pulp.plan.io/issues/3401
I'm not convinced we want to use `choice=` for media_type fields but did at the direction of the story.
> Add docker content models.

- .travis.yml
- pulp_docker/app/models.py
- pulp_docker/app/tasks/publishing.py
- pulp_docker/app/viewsets.py
This patch also updates the publish task to simply create a pass_through Publication.
closes: #3991
https://pulp.plan.io/issues/3991
closes: #3992
https://pulp.plan.io/issues/3992
> Adds models, viewsets, and serializers needed for publishing

- pulp_docker/tests/functional/api/test_sync.py
Test that files are not being left open after sync tasks.
re #4073
https://pulp.plan.io/issues/4073
> Add test for file descriptor leaks

- pulp_docker/tests/functional/api/test_crud_remotes.py
Remove unnecessary repo creation as part of the CRUD remotes tests.
[noissue]
> Simplify test CRUD remotes

- pulp_docker/app/models.py
- pulp_docker/app/tasks/sync_stages.py
- pulp_docker/app/tasks/synchronize.py
- pulp_docker/app/views.py
When syncing, if a tag name references a different manifest/manifest
list it must be removed from the repo. To do this simply, it was more
convinient to split the Tag model into ManifestTag and ManifestListTag.
https://pulp.plan.io/issues/4172
fixes #4172
> Remove non-unique tag names during sync

- pulp_docker/app/models.py
- pulp_docker/app/serializers.py
- pulp_docker/app/tasks/sync_stages.py
- pulp_docker/app/viewsets.py
This commit leaves POST (create) unimplemented as well as Filters which
are each complex enough that they warrent a separate issue and PR.
https://pulp.plan.io/issues/3989
fixes #3989
> Create Serializers and Viewsets for Content

- pulp_docker/tests/functional/api/test_crud_remotes.py
- pulp_docker/tests/functional/constants.py
- pulp_docker/tests/functional/utils.py
Update _gen_verbose_remote to add download policy field. Add constant
DOWNLOAD_POLICIES.
re #4182
https://pulp.plan.io/issues/4182
> Add policy to remote tests

- pulp_docker/tests/functional/api/test_crud_remotes.py
- pulp_docker/tests/functional/constants.py
Simplify constnat `DOWNLOAD_POLICIES` to import from pulp-smash
directly. To be align with the same way that this is done in the other
plugins.
'[noissue]'
> Simplify constant DOWNLOAD_POLICIES import

- pulp_docker/app/tasks/__init__.py
- pulp_docker/app/tasks/distribution.py
- pulp_docker/app/viewsets.py
- pulp_docker/tests/functional/api/test_crud_distributions.py
- pulp_docker/tests/functional/api/test_pull_content.py
Creates functional tests based on regular distributions. Comment out
some failing tests which check functionality that is broken.
https://pulp.plan.io/issues/4582
fixes #4582
> Make docker distribution CUD asynchronous

- pulp_docker/app/serializers.py
- pulp_docker/tests/functional/api/test_crud_distributions.py
Solution: Define the name field on the DockerDistribution serializer
The name field from the BaseDistribution serializer validates that the name doesn't collide
with any other Distributions.
closes: #4600
https://pulp.plan.io/issues/4600
> Problem: DockerDistribution name field not validated correctly

- README.rst
- pulp_docker/app/content.py
- pulp_docker/app/models.py
- pulp_docker/app/registry.py
- pulp_docker/app/tasks/sync_stages.py
- pulp_docker/tests/functional/api/test_pull_content.py
Solution: add support for lazy sync
This patch adds ability to create remotes with policy='on_demand'. When such a remote is used to
sync a repository, the Blobs are not downloaded. Only manifests and manifest lists are saved at
sync time. Blobs are retrieved on demand from clients.
This patch also includes a set of tests that check that you can pull content from a repo that
was synced using a remote that has policy set to 'on_demand'. The tests assert that performing
a docker/podman pull results in more artifacts being stored in Pulp than before the image was
requested.
closes: #4174
https://pulp.plan.io/issues/4174
> Problem: docker plugin does not support lazy sync

- .travis/publish_client_gem.sh
- pulp_docker/__init__.py
- setup.py
A correct version would be shown for installations from the master branch.
Bindings will be generated with a proper version as well.
re #4936
https://pulp.plan.io/issues/4936
> Set version to .dev for the master branch

- CHANGES/5037.bugfix
- pulp_docker/app/tasks/sync_stages.py
Solution: Remove the signatures when calculating the digest.
closes #5037
https://pulp.plan.io/issues/5037
> Problem: Schema1 manifest digest is calculated on the unsigned version.

- pulp_docker/tests/functional/api/test_crud_remotes.py
- pulp_docker/tests/functional/api/test_pull_content.py
The names were updated to replace 'lazy' with 'on demand'.
[noissue]
> Update tests with on-demand terminology.

- docs/workflows/sync.rst
It's a little confusing to have the name be the full upstream name and upstream_name be the abbreviated (but correct) version.  My first assumption running through this with fedora/ssh was that name should have the full upstream name, which was wrong.
> Clarify naming for name and upstream_name

- CHANGES/5470.misc
- pulp_docker/app/tasks/sync_stages.py
closes #5470
https://pulp.plan.io/issues/5470
Required PR: https://github.com/pulp/pulpcore/pull/293
Required PR: https://github.com/pulp/pulpcore-plugin/pull/127
Required PR: https://github.com/pulp/pulp_file/pull/277
> Replace ProgressBar with ProgressReport

- CHANGES/5626.bugfix
- pulp_docker/app/downloaders.py
Use proxy when downloading as is done [here](https://github.com/pulp/pulpcore/blob/e8915ec378a41df1f14feecb15a4399938c5f158/pulpcore/download/http.py#L182).
> Use proxy for downloads

- CHANGES/5562.bugfix
- pulp_docker/app/serializers.py
This reverts commit 8689733ca94c8d67573219e934aa18b2043ec156.
`ref_name` is set automatically now (see https://pulp.plan.io/issues/5574).
[noissue]
> Revert "Explicitly define ref_name on the serializer."
