pulp/pulp_docker

plugins/pulp_docker/plugins/importers/sync.py, plugins/test/unit/plugins/importers/test_sync.py
=> sync no longer clobbers metadata of previously-uploaded images

plugins/pulp_docker/plugins/importers/sync.py, plugins/test/unit/plugins/importers/test_sync.py
fixes #128
https://pulp.plan.io/issues/128
=> sync now validates that a feed and upstream name were specified

extensions_admin/pulp_docker/extensions/admin/cudl.py
This must be merged before https://github.com/pulp/pulp/pull/1703.
=> Fix some incorrect imports.

docs/conf.py
=> Updates extlinks and its usages to use redmine.

docs/tech-reference/distributor.rst
=> add repo-registry-id validation information to docs

common/pulp_docker/common/models.py, common/test/unit/test_models.py, plugins/pulp_docker/plugins/distributors/publish_steps.py, plugins/pulp_docker/plugins/importers/importer.py, plugins/pulp_docker/plugins/importers/sync.py, plugins/pulp_docker/plugins/importers/upload.py, plugins/pulp_docker/plugins/importers/v1_sync.py, plugins/pulp_docker/plugins/registry.py, plugins/test/data/manifest_one_layer.json, plugins/test/data/manifest_repeated_layers.json, plugins/test/data/manifest_unique_layers.json, plugins/test/unit/plugins/distributors/test_metadata.py, plugins/test/unit/plugins/importers/test_importer.py, plugins/test/unit/plugins/importers/test_sync.py, plugins/test/unit/plugins/importers/test_upload.py, plugins/test/unit/plugins/importers/test_v1_sync.py, plugins/test/unit/plugins/test_registry.py, plugins/types/docker.json
https://pulp.plan.io/issues/968
fixes #968
=> Add support to sync with Docker v2 repositories.

plugins/pulp_docker/plugins/distributors/publish_steps.py
=> - typo fix

plugins/pulp_docker/plugins/importers/sync.py, plugins/test/unit/plugins/importers/test_sync.py
=> Removing shutil.move and copytree where /var/cache/pulp is involved.

AUTHORS, common/pulp_docker/common/models.py, extensions_admin/pulp_docker/extensions/admin/cudl.py, plugins/pulp_docker/plugins/distributors/publish_steps.py, plugins/pulp_docker/plugins/registry.py, plugins/test/unit/plugins/test_registry.py
Thanks to Tomáš Tomeček for the code that calculates the Docker Manifest digest included in this commit.
https://pulp.plan.io/issues/1316
closes #1316
=> Add the ability for users to be able to sync from other Pulp servers.

extensions_admin/test/unit/extensions/admin/test_pulp_cli.py
PR #103 had a few style comments about a commit from long ago that was being merged. This commit responds to
those comments with three fixes.
https://github.com/pulp/pulp_docker/pull/103
=> Fix a few style issues mentioned in review comments.

plugins/pulp_docker/plugins/distributors/distributor_export.py, plugins/pulp_docker/plugins/distributors/distributor_web.py, plugins/test/unit/plugins/distributors/test_distributor_export.py, plugins/test/unit/plugins/distributors/test_distributor_web.py
closes #1365
https://pulp.plan.io/issues/1365
=> Removing a Docker repository can cause a TypeError.

plugins/pulp_docker/plugins/importers/sync.py, plugins/pulp_docker/plugins/importers/v1_sync.py, plugins/pulp_docker/plugins/models.py, plugins/test/unit/plugins/importers/test_sync.py, plugins/test/unit/plugins/test_models.py
https://pulp.plan.io/issues/1422
=> ref #1422 - compatibility with lazy platform.

common/pulp_docker/common/constants.py, docs/user-guide/configuration.rst, extensions_admin/pulp_docker/extensions/admin/cudl.py, extensions_admin/test/unit/extensions/admin/test_cudl.py, plugins/pulp_docker/plugins/importers/sync.py, plugins/test/unit/plugins/importers/test_sync.py
https://pulp.plan.io/issues/1597
=> Support v2 enabled importer configuration property.

AUTHORS
=> Add Patrick to authors file

plugins/pulp_docker/plugins/importers/sync.py
Update tag and manifest counts during sync for the
sync report
closes #[1638](https://pulp.plan.io/issues/1638)
https://pulp.plan.io/issues/1638
=> Update tag and manifest counts during sync

plugins/pulp_docker/plugins/importers/upload.py
Fix upload step attributes for v1 upload.
closes #[1650](https://pulp.plan.io/issues/1650)
https://pulp.plan.io/issues/1650
=> Fix upload step attributes for v1

docs/index.rst, docs/tech-reference/distributor.rst, docs/tech-reference/importer.rst, docs/tech-reference/tags.rst, docs/user-guide/concepts.rst, docs/user-guide/configuration.rst, docs/user-guide/installation.rst, docs/user-guide/recipes.rst
https://pulp.plan.io/issues/1163
fixes #1163
=> Update the documentation to reflect the v2 changes.

extensions_admin/pulp_docker/extensions/admin/cudl.py
Our Docker CLI extensions had an oversight where users could not
update the --enable-v{1,2} flags on their repositories. This
commit fixes that oversight.
https://pulp.plan.io/issues/1710
fixes #1710
Instead of unit tests I added a pulp-smash test to ensure that this works correctly (and stays working):
https://github.com/PulpQE/pulp-smash/pull/129
=> Allow users to --enable-v{1,2} with repo update.

extensions_admin/pulp_docker/extensions/admin/images.py
closes #1693
https://pulp.plan.io/issues/1693
=> Force search to include require field

docs/user-guide/recipes.rst
=> add v1 deprecation to recipe

plugins/pulp_docker/plugins/importers/sync.py
=> Adds check for duplicate unit key

plugins/pulp_docker/plugins/importers/importer.py, plugins/test/unit/plugins/importers/test_importer.py
re #1747
https://pulp.plan.io/issues/1747
=> Fix return value of upload_unit() to be consistent with plugin API

plugins/pulp_docker/plugins/migrations/0002_standard_storage_path.py, plugins/test/unit/plugins/migrations/test_0002_standard_storage_path.py
=> standard storage path migration.

plugins/pulp_docker/plugins/importers/sync.py
https://pulp.plan.io/issues/1909
=> Fix syntax error

docs/user-guide/configuration.rst
Fixes: https://pulp.plan.io/issues/1571
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
=> Update link which points to pulp_docker documentation

test_requirements.txt
https://pulp.plan.io/issues/2106
=> pin to flake8-2.6.2 for py2.6 support

docs/tech-reference/distributor.rst
fixes: #2120
https://pulp.plan.io/issues/2120
=> JSON lexer not supported on el7

plugins/pulp_docker/plugins/importers/sync.py
closes #2142
https://pulp.plan.io/issues/2142
=> Stops sync on any download failures

docs/tech-reference/distributor.rst
re #2199
https://pulp.plan.io/issues/2199
=> Additional documentation for rsync distributor

plugins/pulp_docker/plugins/models.py
closes#2198
https://pulp.plan.io/issues/2198
=> With docker_tag unit change _last_updated is changed accordingly

dist_list.txt, docs/tech-reference/distributor.rst, plugins/pulp_docker/plugins/distributors/publish_steps.py, plugins/pulp_docker/plugins/importers/sync.py, plugins/pulp_docker/plugins/models.py
There were no conflicts with this merge.
=> Merge master to 3.0 dev

extensions_admin/setup.py, plugins/setup.py, pulp-dev.py, run-tests.py
closes #2295
https://pulp.plan.io/issues/2295
=> Pulp3: Rewrite shebangs to python3

plugins/pulp_docker/plugins/importers/importer.py
closes #2441
https://pulp.plan.io/issues/2441
=> Blobs with manifest references should not be removed.

docs/conf.py, docs/user-guide/release-notes/1.0.x.rst, docs/user-guide/release-notes/2.0.x.rst, docs/user-guide/release-notes/2.1.x.rst, docs/user-guide/release-notes/2.2.x.rst, docs/user-guide/release-notes/2.3.x.rst
re #2585
https://pulp.plan.io/issues/2585
=> Modify directive name to generate docs correctly using platfrom config

plugins/pulp_docker/plugins/distributors/configuration.py, plugins/test/unit/plugins/distributors/test_configuration.py
https://pulp.plan.io/issues/2368
=> provide synced images with multiple "/" in them.

plugins/pulp_docker/plugins/token_util.py, plugins/test/unit/plugins/test_token_util.py
closes #2644
https://pulp.plan.io/issues/2644
=> Token scope resource can have several resource actions.

pulp-docker.spec
Add obsoletes to spec
refs #[2639](https://pulp.plan.io/issues/2639)
=> Add obsoletes to spec

docs/tech-reference/distributor.rst, docs/user-guide/release-notes/2.5.x.rst, docs/user-guide/release-notes/index.rst
This PR is required to be merged along with pulp/pulp#3026
ref #2730
=> Added documentation for new 'rsync_extra_arg'

docs/user-guide/recipes.rst
closes #2735
https://pulp.plan.io/issues/2735
=> Add docs about v1 protocol limitation.

plugins/pulp_docker/plugins/registry.py
closes #2924
https://pulp.plan.io/issues/2924
=> Accept headers are not correct during the request to the registry.

common/pulp_docker/common/constants.py, plugins/pulp_docker/plugins/importers/sync.py, plugins/pulp_docker/plugins/models.py
closes #2847
https://pulp.plan.io/issues/2847
=> Skip download of blobs with foreign mediatype.

plugins/pulp_docker/plugins/auth_util.py, plugins/pulp_docker/plugins/importers/sync.py, plugins/pulp_docker/plugins/registry.py, plugins/test/unit/plugins/importers/test_sync.py, plugins/test/unit/plugins/test_auth_util.py, plugins/test/unit/plugins/test_registry.py
closes #2956
https://pulp.plan.io/issues/2956
=> Use basic auth to sync when scheme is "basic"

plugins/pulp_docker/plugins/registry.py
Uppstream docker distribution issue:
https://github.com/docker/distribution/pull/2310
=> Disable digest check for image manifest schema2.

common/pulp_docker/common/constants.py, common/pulp_docker/common/error_codes.py, docs/user-guide/recipes.rst, docs/user-guide/release-notes/3.1.x.rst, extensions_admin/pulp_docker/extensions/admin/upload.py, plugins/pulp_docker/plugins/importers/upload.py, plugins/pulp_docker/plugins/models.py, plugins/pulp_docker/plugins/registry.py, plugins/test/unit/plugins/test_models.py
https://pulp.plan.io/issues/2993
=> Feature: Upload docker manifest lists

plugins/pulp_docker/plugins/importers/sync.py, plugins/pulp_docker/plugins/registry.py, plugins/test/unit/plugins/test_registry.py
closes #3139
https://pulp.plan.io/issues/3139
=> Set properly the headers for the sync from Crane usecase.

plugins/pulp_docker/plugins/distributors/configuration.py, plugins/test/unit/plugins/distributors/test_configuration.py
closes #3118
https://pulp.plan.io/issues/3118
=> Update regexp so it would allow repeated dash and double underscore.

common/pulp_docker/common/error_codes.py, plugins/pulp_docker/plugins/importers/upload.py, plugins/test/unit/plugins/importers/test_upload.py
=> Verify blob checksum

docs/user-guide/release-notes/3.1.x.rst, plugins/pulp_docker/plugins/importers/importer.py, plugins/pulp_docker/plugins/importers/upload.py, plugins/pulp_docker/plugins/importers/v1_sync.py, plugins/test/unit/plugins/importers/test_importer.py, plugins/test/unit/plugins/importers/test_upload.py
closes https://pulp.plan.io/issues/3232
=> upload_unit returns the unit key for what got uploaded

plugins/pulp_docker/plugins/importers/sync.py, plugins/pulp_docker/plugins/registry.py
closes #3286
https://pulp.plan.io/issues/3286
=> Sync logic should not assume on schema1 by default existence.

docs/user-guide/recipes.rst
closes #3258
https://pulp.plan.io/issues/3258
=> Update with new recipe for v2s1 manifest upload.

plugins/pulp_docker/plugins/auth_util.py, plugins/pulp_docker/plugins/importers/sync.py, plugins/pulp_docker/plugins/registry.py, plugins/test/unit/plugins/test_auth_util.py
closes #3573
https://pulp.plan.io/issues/3573
=> Enable sync from google registry.

plugins/pulp_docker/plugins/auth_util.py, plugins/pulp_docker/plugins/registry.py
closes #3686
https://pulp.plan.io/issues/3686
=> Misleading error when trying to sync private repo with wrong creds

extensions_admin/pulp_docker/extensions/admin/upload.py
closes #3667
https://pulp.plan.io/issues/3667
=> Merrory error when trying to upload a big tar.

common/pulp_docker/common/constants.py, docs/tech-reference/importer.rst, docs/user-guide/configuration.rst, docs/user-guide/recipes.rst, docs/user-guide/release-notes/3.2.x.rst, extensions_admin/pulp_docker/extensions/admin/cudl.py, plugins/pulp_docker/plugins/importers/sync.py, plugins/test/unit/plugins/importers/test_sync.py
closes #3450
https://pulp.plan.io/issues/3450
=> Support Tag Whitelisting

plugins/pulp_docker/plugins/importers/upload.py, plugins/test/unit/plugins/importers/test_upload.py
https://pulp.plan.io/issues/3757
The `AddUnits` flow has been changed.  The `get_iterator()` returns an iterator for a _complete_ list of: `Manifest` and validated `Blobs` that are not already in the repository. As a result, an exception can be raised for missing of invalid blobs before anything is added in the DB.
The `process_main()` was doing too much and this was a good opportunity to refactor it.
I changed the import of `transport.Version` mainly to reduce ink.
=> Partial blobs not added during failed upload.

plugins/pulp_docker/plugins/importers/importer.py
https://pulp.plan.io/issues/3892
re #3137
closes #3892
=> Fix issue with associating embedded manifests in manifest list

plugins/pulp_docker/plugins/registry.py
closes #3960
https://pulp.plan.io/issues/3960
=> Add support to handle pagination for tags/list endpoint.

pulp_docker/app/models.py, pulp_docker/app/tasks/publishing.py
=> Makes use of Publication context manager

docs/user-guide/release-notes/3.2.x.rst
(cherry picked from commit 41cf057dc7a4ac33a0e15a32e425e85f548209b2)
=> 3.2.1 release notes cherry-pick

common/pulp_docker/common/error_codes.py, plugins/pulp_docker/plugins/importers/sync.py
https://pulp.plan.io/issues/2966
https://pulp.plan.io/issues/2849
fixes #2849
=> Fail gracefully when image download fails.

pulp_docker/app/tasks/sync_stages.py
Solution: Create a new ContentArtifact for a Manifest after downloading it
The ContentArtifact from the Tag that was used to download the Manifest or ManifestList was
being reused for the Manifest or ManifestList. This patch ensures that a new ContentArtifact
is created after the download is complete.
[noissue]
=> Problem: Some ContentArtifacts contain wrong relative_path

README.rst
=> Fix a typo in readme

README.rst, pulp_docker/app/serializers.py, pulp_docker/app/tasks/publishing.py, pulp_docker/app/urls.py, pulp_docker/app/views.py, pulp_docker/app/viewsets.py
Solution: add registry APIs needed for docker pull
closes: #3994
https://pulp.plan.io/issues/3994
closes: #3995
https://pulp.plan.io/issues/3995
=> Problem: docker client can't pull from pulp_docker

pulp_docker/tests/functional/api/test_crud_content_unit.py
For a brief period Pulp would allow you to delete a content unit as long
as it wasn't used by a repository version. That is no longer the case -
content unit deletion should be disallowed in all circumstances. Fix the
tests likewise, and test that the response is HTTP 405 'method not allowed', specifically.
re #4216
https://pulp.plan.io/issues/4216
=> Simplify content unit deletion test

plugins/pulp_docker/plugins/importers/importer.py
https://pulp.plan.io/issues/3896
=> Better upload error reporting. re: issue-3896

.travis/before_script.sh, .travis/script.sh, README.rst
https://pulp.plan.io/issues/3693
re #3693
=> Fixes Travis from Lazy changes

pulp_docker/tests/functional/api/test_publish.py, pulp_docker/tests/functional/api/test_sync.py, pulp_docker/tests/functional/constants.py, pulp_docker/tests/functional/utils.py
Required PR: https://github.com/pulp/pulp/pull/3805
[noissue]
=> Adapting pulp_smash tests to new schema

.travis/script.sh
=> fix travis for pulpcore update (commit migrations)

pulp_docker/app/tasks/dedupe_save.py, pulp_docker/app/tasks/synchronize.py
https://pulp.plan.io/issues/4177
fixes #4177
=> Replace SerialArtifactSave with ArtifactSaver.

.travis.yml, setup.py
=> Adds PyPI config for releasing tagged commits

setup.py
=> Bumber docker version to beta.

.travis.yml
=> Fix indentation in yml file.

.travis/script.sh, README.rst, pulp_docker/app/__init__.py, pulp_docker/app/viewsets.py, pulp_docker/tests/functional/constants.py
re #4279
https://pulp.plan.io/issues/4279
Required PR: https://github.com/pulp/pulp/pull/3836
=> Change Django app label and adjust `endpoint_name`s

pulp_docker/app/models.py, pulp_docker/app/registry.py, pulp_docker/app/serializers.py, pulp_docker/app/tasks/dedupe_save.py, pulp_docker/app/tasks/sync_stages.py, pulp_docker/app/tasks/synchronize.py, setup.py
https://pulp.plan.io/issues/4381
=> Fix plugin API 0.01b18 compat.

docs/user-guide/recipes.rst
=> Add warning about index.docker.io usage

pulp_docker/app/models.py, pulp_docker/app/tasks/sync_stages.py
https://pulp.plan.io/issues/4171
=> Support include/exclude of foreign layers.

plugins/pulp_docker/plugins/importers/sync.py, plugins/test/unit/plugins/importers/test_sync.py
closes #4328
https://pulp.plan.io/issues/4328
=> Check for returned mediatype from the registry

plugins/etc/httpd/conf.d/pulp_docker.conf
closes #4364
https://pulp.plan.io/issues/4384
=> Update apache confing to return signed schema1 mediatype.

.travis/script.sh, README.rst
closes #4187
https://pulp.plan.io/issues/4187
=> Use hyphens for Pulp3' systemd units name.

pulp_docker/tests/functional/api/test_crud_content_unit.py, pulp_docker/tests/functional/api/test_crud_publishers.py, pulp_docker/tests/functional/api/test_download_content.py, pulp_docker/tests/functional/api/test_publish.py, pulp_docker/tests/functional/api/test_sync.py, pulp_docker/tests/functional/constants.py, pulp_docker/tests/functional/utils.py
Some functional test cases were migrated to this repo
with the comment `FIXME:`
This PR implements the missing helper methods and adjust the
constants to fix all the existing test cases.
[noissue]
=> Fix all existing functional test cases

.travis/before_script.sh, .travis/install.sh, .travis/script.sh
re: #4444
https://pulp.plan.io/issues/4444
=> Switches Travis to use pulpcore repo

CODEOWNERS
=> Give ownership of functional tests to QE

pulp_docker/app/serializers.py
Solution: update the DockerDistribution serializer to use the BaseDistributionSerializer
re: #4435
https://pulp.plan.io/issues/4435
re: #4437
https://pulp.plan.io/issues/4437
=> Problem: plugin code is not using new plugin API serializer

.travis/install.sh, pulp_docker/app/tasks/dedupe_save.py
=> Install pulpcore with postgresql extra packages

README.rst
=> Add more information to README.rst

docs/user-guide/release-notes/3.2.x.rst
=> Add release notes for 3.2.3

.travis/script.sh, README.rst
Solution: use django-admin directly
re: #4450
https://pulp.plan.io/issues/4450
=> Problem: pulp-manager is not needed

pulp_docker/app/registry.py, setup.py
Solution: prepend the MEDIA_ROOT to the path before trying to send the artifcat
fixes: #4583
https://pulp.plan.io/issues/4583
=> Problem: registry is using relative path to serve artifact

README.rst
closes #4514
https://pulp.plan.io/issues/4514
=> Update docs to use UUIDs.

README.rst
Solution: fix the typo
[noissue]
=> Problem: README instructions have typo

.travis/install.sh, .travis/script.sh, README.rst
Change Pulp 3 Default Ports
https://pulp.plan.io/issues/4556
docs updates too:
https://pulp.plan.io/issues/4594
Content: 8080 -> 24816
API: 8000 -> 24817
[noissue]
Required PR: https://github.com/pulp/pulpcore/pull/75
=> Default ports

pulp_docker/app/models.py, pulp_docker/app/registry.py
closes #4736
https://pulp.plan.io/issues/4736
=> Cannot pull schema1 by tag.

README.rst, pulp_docker/app/models.py, pulp_docker/app/serializers.py, pulp_docker/app/tasks/sync_stages.py
closes #4169
https://pulp.plan.io/issues/4169
=> As a user i can whitelist tags when syncing from a registry.

docs/tech-reference/importer.rst, docs/user-guide/configuration.rst, docs/user-guide/recipes.rst, docs/user-guide/release-notes/3.2.x.rst, extensions_admin/pulp_docker/extensions/admin/cudl.py, plugins/pulp_docker/plugins/importers/sync.py
closes #4597
https://pulp.plan.io/issues/4597
=> Deprecate docker v1 support

pulp_docker/app/downloaders.py, pulp_docker/app/models.py
This PR enables sync from the registries that use basic auth or
token auth but repos are protected or private.
closes #4717
closes #4808
https://pulp.plan.io/issues/4717
https://pulp.plan.io/issues/4808
=> As a user, I can sync from registries that use basic auth.

pulp_docker/app/downloaders.py, pulp_docker/app/registry.py
Solution: use the Handler from pulpcore-plugin
[noissue]
=> Problem: registry code duplicates code from pulpcore

docs/workflows/publish.rst, docs/workflows/sync.rst
Solution: update docs with port 24817
[noissue]
=> Problem: docs state to use port 8000

pulp_docker/tests/functional/api/test_crud_distributions.py
closes #4599
https://pulp.plan.io/issues/4599
=> Add filters for DockerDistributions.

pulp_docker/__init__.py
https://pulp.plan.io/issues/4875
re #4875
=> Fix __version__ to use correct package name

.travis.yml, .travis/before_install.sh, .travis/before_script.sh, .travis/check_commit.sh, .travis/install.sh, .travis/mariadb.yml, .travis/playbook.yml, .travis/postgres.yml, .travis/publish_client_gem.sh, .travis/publish_client_pypi.sh, .travis/publish_plugin_pypi.sh, .travis/script.sh, .travis/validate_commit_message.py, doc_requirements.txt
Solution: generate the config using travis config generator
closes: #4572
https://pulp.plan.io/issues/4572
=> Problem: plugin repo does not use standard travis config for plugins

.travis.yml, .travis/publish_client_pypi.sh, .travis/script.sh
Also fixes version for pypi publish
=> Update travis scripts

.travis/publish_client_gem.sh, .travis/publish_client_pypi.sh, .travis/script.sh
Solution: remove the extra '.' from the version string
[noissue]
=> Problem: client is not publishing to PyPI

CHANGES/4646.bugfix, pulp_docker/app/registry.py, pulp_docker/app/serializers.py, pulp_docker/tests/functional/api/test_crud_remotes.py
closes #4646
https://pulp.plan.io/issues/4646
=> Add 'Docker-Content-Digest' header to the reasponse headers.

pulp_docker/__init__.py, setup.py
=> Version bump to 4.0.0b6.dev for the master branch after release

test_requirements.txt
=> Temporarily pin pydocstyle.

pulp_docker/app/viewsets.py
=> Change detail_route to action for DRF 3.10

plugins/pulp_docker/plugins/importers/importer.py, plugins/test/unit/plugins/importers/test_importer.py
https://pulp.plan.io/issues/4549
Replace the recursive pattern with a fixed number of larger queries.
Additionally, reorder the content removal to "top down". This will fail
more gracefully; failure leaves orphans (safe) rather than user-facing
unlinked content (unsafe). This requires the additional plugin step of
removing the explicitly given content, which is normally handled by pulp
platform.
A side effect of this change is the correction of a bug that did not
remove shared content, even if all linked content is removed.
https://pulp.plan.io/issues/5161
All the unit tests are removed because they have been broken and skipped since 2015. Replacement tests should be functional, not unit tests anyway.
fixes #5161
fixes #4549
=> Flatten queries for content unit removal

.travis/playbook.yml
=> Problem: travis user is assigned to group 'pulp'

pulp_docker/app/viewsets.py
closes #5182
https://pulp.plan.io/issues/5182
=> As a user I can filter char fields by multiple values

CHANGES/4934.feature, docs/workflows/index.rst, docs/workflows/tagging.rst, pulp_docker/app/serializers.py, pulp_docker/app/tasks/__init__.py, pulp_docker/app/tasks/tag.py, pulp_docker/app/tasks/untag.py, pulp_docker/app/urls.py, pulp_docker/app/viewsets.py, pulp_docker/tests/functional/api/test_tagging_images.py, pulp_docker/tests/functional/constants.py
closes #4934
https://pulp.plan.io/issues/4934
=> Enable users to tag and untag manifests

CHANGES/5252.bugfix, pulp_docker/app/tasks/sync_stages.py, pulp_docker/tests/functional/api/test_sync.py
https://pulp.plan.io/issues/5252
fixes #5252
=> Fix bug, repeated sync creates orphan invalid tags

CHANGES/4737.feature, pulp_docker/app/tasks/sync_stages.py
closes #4737
https://pulp.plan.io/issues/4737
=> As a user I can sync from a docker repo published by Pulp.

pulp_docker/tests/functional/api/test_tagging_images.py
Created resources are not checked within tasks anymore. This
allows the tests to be executed repeatedly without ensuring
that a database is clean.
Also, manifest tags are now filtered by a latest repository
version.
[noissue]
=> Assert added contents instead of created resources

CHANGES/5211.bugfix
=> Expand release notes.

pulp_docker/app/tasks/sync_stages.py
=> Get number of total tags before finishing the task

pulp_docker/__init__.py, setup.py
=> Version bump to 4.0.0b8.dev for the master branch after release.

pulp_docker/tests/functional/api/test_crud_distributions.py, setup.py
=> Version bump in setup.py

pulp_docker/app/viewsets.py
=> Switch to ReadOnlyContentViewset.

CHANGES/5548.removal, docs/workflows/sync.rst, pulp_docker/tests/functional/api/test_pull_content.py, pulp_docker/tests/functional/api/test_recursive_add.py, pulp_docker/tests/functional/api/test_recursive_remove.py, pulp_docker/tests/functional/api/test_sync.py, pulp_docker/tests/functional/api/test_tagging_images.py
_versions_href to pulp_versions_href
_latest_version_href to pulp_latest_version_href
ref #5548
https://pulp.plan.io/issues/5548
Required PR: https://github.com/pulp/pulpcore/pull/329
Required PR: https://github.com/PulpQE/pulp-smash/pull/1221
=> Renaming RepositoryVersion fields

CHANGES/5562.bugfix, pulp_docker/app/serializers.py
=> Explicitly define ref_name on the serializer.

.travis.yml, .travis/before_install.sh, .travis/install.sh, .travis/script.sh, CHANGES/5580.misc
Required PR: https://github.com/pulp/pulpcore/pull/347
re: #5580
https://pulp.plan.io/issues/5580
=> Depend on pulpcore directly instead of pulpcore-plugin

CHANGES/4244.feature, functest_requirements.txt, pulp_docker/app/docker_convert.py, pulp_docker/app/registry.py, pulp_docker/tests/functional/test_convert.py
closes #4244
https://pulp.plan.io/issues/4244
=> Execute implemented schema conversion from the registry

.travis/install.sh, pulp_docker/app/authorization.py, pulp_docker/app/serializers.py, pulp_docker/app/token_verification.py, template_config.yml
Required PR: https://github.com/pulp/pulpcore/pull/358
Required PR: https://github.com/PulpQE/pulp-smash/pull/1227
[noissue]
=> Remove content_origin and let pulp-operator auto set it.
